services:
  - type: web
    name: affecto-backend
    env: python
    region: oregon
    plan: free
    runtime: python-3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: HF_SPACE_URL
        value: https://gauravvjhaaok-affecto-inference.hf.space
